CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    address VARCHAR(500),
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_customer_number UNIQUE (customer_number)
);

CREATE TABLE IF NOT EXISTS meters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_number VARCHAR(255) NOT NULL,
    installation_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    tariff_type VARCHAR(32) NOT NULL DEFAULT 'RESIDENTIAL',
    customer_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_meter_number UNIQUE (meter_number),
    CONSTRAINT fk_meters_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE IF NOT EXISTS meter_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_date DATE NOT NULL,
    reading_value NUMERIC(12, 2) NOT NULL,
    meter_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_reading_meter_date UNIQUE (meter_id, reading_date),
    CONSTRAINT fk_readings_meter FOREIGN KEY (meter_id) REFERENCES meters (id)
);

CREATE INDEX IF NOT EXISTS idx_reading_meter_date ON meter_readings (meter_id, reading_date);

CREATE TABLE IF NOT EXISTS tariff_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_type VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_tariff_type_version UNIQUE (tariff_type, version)
);

CREATE INDEX IF NOT EXISTS idx_tariff_type_dates ON tariff_plans (tariff_type, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS tariff_slabs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    from_units NUMERIC(12, 2) NOT NULL,
    to_units NUMERIC(12, 2),
    rate_per_unit NUMERIC(12, 2) NOT NULL,
    tariff_plan_id BIGINT NOT NULL,
    CONSTRAINT fk_tariff_slabs_plan FOREIGN KEY (tariff_plan_id) REFERENCES tariff_plans (id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(255) NOT NULL,
    previous_reading NUMERIC(12, 2) NOT NULL,
    current_reading NUMERIC(12, 2) NOT NULL,
    units_consumed NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    tariff_type VARCHAR(32),
    tariff_version INTEGER,
    generated_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    customer_id BIGINT NOT NULL,
    previous_reading_id BIGINT NOT NULL,
    current_reading_id BIGINT NOT NULL,
    tariff_plan_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_invoice_number UNIQUE (invoice_number),
    CONSTRAINT uk_invoice_source_readings UNIQUE (customer_id, previous_reading_id, current_reading_id),
    CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_invoices_previous_reading FOREIGN KEY (previous_reading_id) REFERENCES meter_readings (id),
    CONSTRAINT fk_invoices_current_reading FOREIGN KEY (current_reading_id) REFERENCES meter_readings (id),
    CONSTRAINT fk_invoices_tariff_plan FOREIGN KEY (tariff_plan_id) REFERENCES tariff_plans (id)
);
