ALTER TABLE customers ADD COLUMN IF NOT EXISTS opt_lock BIGINT NOT NULL DEFAULT 0;
ALTER TABLE meters ADD COLUMN IF NOT EXISTS opt_lock BIGINT NOT NULL DEFAULT 0;
ALTER TABLE meter_readings ADD COLUMN IF NOT EXISTS opt_lock BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tariff_plans ADD COLUMN IF NOT EXISTS opt_lock BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tariff_slabs ADD COLUMN IF NOT EXISTS opt_lock BIGINT NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS opt_lock BIGINT NOT NULL DEFAULT 0;
