services:
  mysql:
    image: mysql:8.0
    container_name: ecovolt_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecovolt_billing
      MYSQL_USER: ecovolt_user
      MYSQL_PASSWORD: neeraj


    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d


volumes:
  mysql_data:

